remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

title: Notes
description: Knowledge base
url: https://mazamaka.github.io
baseurl: /notes

defaults:
  - scope:
      path: ""
    values:
      image: /assets/og-default.png
